name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "22"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: |
          if [ -f gradlew ]; then
            chmod +x gradlew
          fi

      - name: Generate Gradle Wrapper if missing
        run: |
          mkdir -p gradle/wrapper

          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Wrapper missing. Generating..."
            gradle wrapper --gradle-version 8.14.3
          else
            echo "Wrapper exists."
          fi

      - name: Verify Wrapper
        run: ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Commit Generated Wrapper
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto generate Gradle Wrapper"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/*.apk
